[package]
name = "ddup-workspace"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "warn"
unimplemented = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
missing_errors_doc = "allow"
doc_markdown = "allow"
needless_pass_by_value = "allow"
too_many_arguments = "allow"
collapsible_if = "allow"

[lints]
workspace = true

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
