[package]
name = "ddup"
version = "0.1.0"
edition = "2024"

[dependencies]
ddup-core = { path = "../ddup-core" }
anyhow = "1.0.102"
arboard = "3.6.1"
clap = { version = "4.5.53", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.30.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[lints]
workspace = true
