[build]
target = "x86_64-pc-windows-gnu"
rustflags = ["-L", "native=C:\\Users\\jm\\Documents\\Codex\\2026-06-02\\files-mentioned-by-the-user-pasted\\linker-shims"]

[target.x86_64-pc-windows-gnu]
linker = "gcc"
